name: cache

on:
  push:
    tags:
    - '*'        

jobs:

  check-dhall:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: dhall-lang/setup-dhall@v4
      with:
        version: '1.31.1'
    - name: cache
      run: |
        export XDG_CACHE_HOME=$PWD/cache
        bin/dhall <<< ./package.dhall 1> /dev/null
    - uses: meeDamian/github-release@v1.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: true
        gzip: true
        files: >
          cache:cache
