name: CI

on: [push]

jobs:

  check-dhall:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Download dhall
      run: |
        curl -sSL https://github.com/dhall-lang/dhall-haskell/releases/download/1.29.0/dhall-1.29.0-x86_64-linux.tar.bz2 | tar -xj  -C .
        sudo mv bin/dhall /usr/local/bin/dhall
    - name: check code
      run: dhall <<< ./package.dhall
    - name: check formatting
      run: find . -name '*.dhall' | xargs -n 1 dhall --ascii format --check --inplace
    - name: compute diff
      run: make diff || true
