name: CI

on: [push]

jobs:

  check-dhall:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: dhall-lang/setup-dhall@v4
      with:
        version: '1.31.1'
    - name: check code
      run: dhall <<< ./package.dhall
    - name: check formatting
      uses: dhall-lang/setup-dhall@v4
      run: find . -name '*.dhall' | xargs -n 1 dhall --ascii format --check --inplace
      with:
        version: '1.31.1'
    - name: compute diff
      uses: dhall-lang/setup-dhall@v4
      run: make diff || true
      with:
        version: '1.31.1'
