name: CI

on: [push]

jobs:

  check-dhall:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Download dhall
      run: curl -sSL https://github.com/dhall-lang/dhall-haskell/releases/download/1.26.0/dhall-1.26.0-x86_64-linux.tar.bz2 | tar -xj  -C .
    - name: check code
      run: bin/dhall <<< ./package.dhall
